routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index');

    //roles
    Route::resource('roles', 'Admin\RolesController');
    Route::post('roles_mass_destroy', ['uses' => 'Admin\RolesController@massDestroy', 'as' => 'roles.mass_destroy']);

    //departments
    Route::resource('departments', 'Admin\DepartmentsController');
    Route::post('departments_mass_destroy', ['uses' => 'Admin\DepartmentsController@massDestroy', 'as' => 'departments.mass_destroy']);
    Route::post('departments_restore/{id}', ['uses' => 'Admin\DepartmentsController@restore', 'as' => 'departments.restore']);
    Route::delete('departments_perma_del/{id}', ['uses' => 'Admin\DepartmentsController@perma_del', 'as' => 'departments.perma_del']);

    //users
    Route::resource('users', 'Admin\UsersController');
    Route::post('users_mass_destroy', ['uses' => 'Admin\UsersController@massDestroy', 'as' => 'users.mass_destroy']);

    //    teachers
    Route::resource('teachers', 'Admin\TeachersController');
    Route::post('teachers_mass_destroy', ['uses' => 'Admin\TeachersController@massDestroy', 'as' => 'teachers.mass_destroy']);
    Route::post('teachers_restore/{id}', ['uses' => 'Admin\TeachersController@restore', 'as' => 'teachers.restore']);
    Route::delete('teachers_perma_del/{id}', ['uses' => 'Admin\TeachersController@perma_del', 'as' => 'teachers.perma_del']);

    //    courses
    Route::resource('courses', 'Admin\CoursesController');
    Route::post('courses_mass_destroy', ['uses' => 'Admin\CoursesController@massDestroy', 'as' => 'courses.mass_destroy']);
    Route::post('courses_restore/{id}', ['uses' => 'Admin\CoursesController@restore', 'as' => 'courses.restore']);
    Route::delete('courses_perma_del/{id}', ['uses' => 'Admin\CoursesController@perma_del', 'as' => 'courses.perma_del']);

    //rooms
    Route::resource('rooms', 'Admin\RoomsController');
    Route::post('rooms_mass_destroy', ['uses' => 'Admin\RoomsController@massDestroy', 'as' => 'rooms.mass_destroy']);
    Route::post('rooms_restore/{id}', ['uses' => 'Admin\RoomsController@restore', 'as' => 'rooms.restore']);
    Route::delete('rooms_perma_del/{id}', ['uses' => 'Admin\RoomsController@perma_del', 'as' => 'rooms.perma_del']);

    //find-rooms
    Route::get('find_rooms', 'Admin\FindRoomsController@index')->name('find_rooms.index');
    Route::post('find_rooms', 'Admin\FindRoomsController@index');

    //bookings
    Route::resource('bookings', 'Admin\BookingsController', ['except' => 'bookings.create']);
    Route::get('bookings/create/', ['as' => 'bookings.create', 'uses' => 'Admin\BookingsController@create']);
    Route::post('bookings_mass_destroy', ['uses' => 'Admin\BookingsController@massDestroy', 'as' => 'bookings.mass_destroy']);
    Route::post('bookings_restore/{id}', ['uses' => 'Admin\BookingsController@restore', 'as' => 'bookings.restore']);
    Route::delete('bookings_perma_del/{id}', ['uses' => 'Admin\BookingsController@perma_del', 'as' => 'bookings.perma_del']);
    Route::put('updateStatus/{id}', ['uses' => 'Admin\BookingsController@updateStatus', 'as' => 'bookings.updateStatus']);

    // Change Password Routes...
    Route::get('change_password', 'Auth\ChangePasswordController@showChangePasswordForm')->name('auth.change_password');
    Route::patch('change_password', 'Auth\ChangePasswordController@changePassword')->name('auth.change_password');
});


Auth::routes();

app/Http/Controllers/Admin/FindRoomsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Room;
use App\RoomAvail;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;
use App\Http\Controllers\Controller;

class FindRoomsController extends Controller
{
    public function index(Request $request)
    {
        if (!Gate::allows('find_room_access')) {
            return abort(401);
        }
        $time_from = $request->input('time_from');
        $time_to = $request->input('time_to');
        $rooms = null;

        if ($request->isMethod('POST')) {

            $dayFrom = array_search(timeFormat('l', $time_from), days());
            $dayTo = array_search(timeFormat('l', $time_to), days());
            $dayTimeFrom = timeFormat('H:i', $time_from);
            $dayTimeTo = timeFormat('H:i', $time_to);

            $avail = RoomAvail::whereBetween('day', [$dayFrom, $dayTo])
                ->whereBetween('time_from', [$dayTimeFrom, $dayTimeTo])
                ->whereBetween('time_to', [$dayTimeFrom, $dayTimeTo])
                ->pluck('room_id')->toArray();

            $rooms = Room::with(['booking' => function ($q) use ($time_from, $time_to) {
                $q->where(function ($q2) use ($time_from, $time_to) {
                    $q2->orderBy('time_from', 'desc');
                    $q2->whereBetween('time_from', [convertTime($time_from, 24), convertTime($time_to, 24)])
                        ->orWhereBetween('time_to', [convertTime($time_from, 24), convertTime($time_to, 24)]);

                });
            }])->whereIn('id', $avail)->get();
        }

        return view('admin.find_rooms.index', compact('rooms', 'time_from', 'time_to'));
    }

}

resources/views/admin/find_rooms/booking.blade.php
<table class="table table-bordered table-striped datatable">
    <thead>
    <tr>
        <th>{{ transFunc('bookings.fields.course') }}</th>
        <th>{{ transFunc('courses.fields.teacher') }}</th>
        <th>@lang('quickadmin.bookings.fields.time-from')</th>
        <th>@lang('quickadmin.bookings.fields.time-to')</th>
        <th>{{ transFunc('bookings.fields.status') }}</th>
        <th></th>
    </tr>
    </thead>

    <tbody>
    @foreach ( $room->booking as $booking)
        <tr data-entry-id="{{ $booking->id }}">
            <td field-key='course'>{{ $booking->course->code." [".$booking->course->name."]" }}</td>
            <td field-key='course'>{{ $booking->course->teacher->name." [".$booking->course->teacher->desig."]" }}</td>
            <td field-key='time_from'>{{ $booking->time_from }}</td>
            <td field-key='time_to'>{{ $booking->time_to }}</td>
            <td>{!! status()[$booking->status] !!}</td>
            <td>
                @can('booking_view')
                    <a href="{{ route('bookings.show',[$booking->id]) }}" target="_blank"
                       class="btn btn-xs btn-primary">@lang('quickadmin.qa_view')</a>
                @endcan
            </td>
        </tr>
    @endforeach
    </tbody>
</table>

resources/views/admin/find_rooms/index.blade.php
@extends('layouts.app')

@section('content')
    <h3 class="page-title">@lang('quickadmin.find-room.title')</h3>
    <div class="panel panel-default">

        {!! Form::open(['method' => 'post', 'route' => ['find_rooms.index']]) !!}
        <div class="row" style="margin-top: 5px;">
            <div class="col-xs-9">
                <div class="col-xs-6 form-group">
                    {!! Form::label('time_from', trans('quickadmin.bookings.fields.time-from').'*', ['class' => 'control-label']) !!}
                    {!! Form::text('time_from', $time_from, ['class' => 'form-control datetimepicker', 'placeholder' => '', 'required' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('time_from'))
                        <p class="help-block">
                            {{ $errors->first('time_from') }}
                        </p>
                    @endif
                </div>
                <div class="col-xs-6 form-group">
                    {!! Form::label('time_to', trans('quickadmin.bookings.fields.time-to').'*', ['class' => 'control-label']) !!}
                    {!! Form::text('time_to', $time_to, ['class' => 'form-control datetimepicker', 'placeholder' => '', 'required' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('time_to'))
                        <p class="help-block">
                            {{ $errors->first('time_to') }}
                        </p>
                    @endif
                </div>
            </div>
            <div class="col-xs-2">
                <div class="form-group" style="margin-top: 5px;">
                    <label class="control-label"></label>
                    {!! Form::submit('Search for rooms', ['class' => 'btn btn-danger btn-block']) !!}
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
        @if (isset($rooms) && is_null($rooms))
            <div class="form-group" style="text-align: center">
                <label>@lang('quickadmin.find-room.no_rooms_found')</label>
            </div>
        @endif
        @if ($rooms)
            <div class="panel-body table-responsive">
                <table class="table table-bordered table-striped">
                    <thead>
                    <tr>
                        <th>@lang('quickadmin.rooms.fields.room-number')</th>
                        <th>{{ transFunc('find-room.book_history') }}</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach ($rooms as $room)
                        <tr data-entry-id="{{ $room->id }}">
                            <td field-key='room_number'>{{ $room->room_number." [".$room->floor."]" }}</td>
                            <td field-key='history'>
                                @if($bookCount = count( $room->booking) > 0)
                                    @include('admin.find_rooms.booking')
                                @else
                                    Available
                                @endif
                            </td>
                            <td>
                                @can('booking_create')
                                    <button class="btn btn-danger" {{ $bookCount ? 'disabled' : '' }}>
                                        <a style="color: #ffffff;" href="{{ $bookCount ? '#':route('bookings.create',
                                        ['room_id' => $room->id,'time_from' => $time_from, 'time_to' => $time_to]) }}" target="_blank">
                                            {!!trans('quickadmin.find-room.book_room')!!}
                                        </a>
                                    </button>
                                @endcan
                                    {!! $bookCount ? '<br><span style="color: red">Unavailable</span' : '' !!}
                            </td>
                        </tr>
                    @endforeach
                    @endif
                    </tbody>
                </table>
            </div>
    </div>
@stop
@section('javascript')
    @parent
    <script src="https://cdn.datatables.net/select/1.2.0/js/dataTables.select.min.js"></script>
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/css/bootstrap-datetimepicker.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.20.1/moment.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/js/bootstrap-datetimepicker.min.js"></script>
    <script>
        $('.datetimepicker').datetimepicker({
            format: "YYYY-MM-DD hh:mm A"
        });
    </script>
@stop